### PR TITLE
image_builder: fix: disable dtparam in chroot

### PR DESCRIPTION
**Pull request by urpylka**
After replacement https://github.com/CopterExpress/clever/commit/0346c48546590faa00f7ee0a1d0ea71f6343bd17 our forked-scripts to `raspi-config` I meet problem that `raspi-config` not correct work in chroot.

And now I made hack to replace `dtparam` to stopper script.
P.S. After next session `PATH` is become normal. And script self-removed.

Any ideas?

More information you can find there https://github.com/CopterExpress/clever/issues/38

### CODE REVIEW

**Comment by dvornikov-aa** [comment]
Are you going to make a pull request for this feature?

**Comment by urpylka** [comment]
@dvornikov-aa I want to make PR, but I don't know how I can do it. I have two options:
1. **chroot-check** (but it's not correct - ideal chroot invisible)
2. **additional param** for manual disable several functions like `dtparam`

**Comment by dvornikov-aa** [comment]
@urpylka I think it's better to discuss the issue with raspi-config developers before making pull request.

**Comment by urpylka** [comment]
@dvornikov-aa OK, but what we doing with this PR (in our repo)?

**Comment by urpylka** [comment]
I removed the branch, if you need see commit in this PR

**Pull request closed without merging**
