### PR TITLE
Install pyzbar to image

### PR DESCRIPTION
**Pull request by goldarte**
I suggest installing pyzbar to RPi image for making barcodes scanning easier during different competitions.

### CODE REVIEW

**Comment by okalachev** [comment]
Isn't this library too specific?

**Comment by goldarte** [comment]
> Isn't this library too specific?

Maybe.

**Comment by okalachev** [comment]
Anyway, it should be mentioned in the docs, that this is installed.

**Comment by sfalexrog** [comment]
I'd love to see a test for the library. Other than that, looks good to me!

**Comment by goldarte** [comment]
Added tests and update docs as much as possible.

**Comment by okalachev** [comment]
OK, tests passed.

**Pull request merged**
