### PR TITLE
Log formatting

### PR DESCRIPTION
**Pull request by sfalexrog**
Change default log formatting for log messages (add node names to them).

### CODE REVIEW

**Comment by okalachev** [comment]
But we also should change all our nodes code, removing the leading nodes name from logging, don't we?

**Comment by sfalexrog** [comment]
Well, that didn't work so well for nodelets (they report their node name, which is `nodelet_manager` most of the time). Any suggestions?

**Comment by sfalexrog** [comment]
Turns out there's already a set of nodelet-aware macros for `rosconsole` (`NODELET_INFO`, `NODELET_WARN`, etc). I've reworked our nodelet logging code in https://github.com/CopterExpress/clever/pull/175/commits/a49d537fa4e51457bdfaf1534ddcf0efa8715ef5 to use them.
Also, I'm using the logger name, which typically contains node name, but may also contain additional data (such as a node's subsystem for complex nodes like `mavros`). This should still result in a decent `selfcheck.py` output.

**Comment by okalachev** [comment]
@sfalexrog, please, resolve a conflict.

**Pull request merged**
