### PR TITLE
Fix network documentation in the English gitbook

### PR DESCRIPTION
**Pull request by hany606**
In the English documentation, the part of "Switching the adapter to the access point mode" is not working due to restart of dhcpcd service before enabling dnsmasq service.

### CODE REVIEW

**Comment by okalachev** [comment]
@urpylka, @sfalexrog, please, have a look.

**Comment by urpylka** [comment]
@hany606 you are right. I think it’s mistake in translation. Russian [version](https://github.com/CopterExpress/clever/blob/master/docs/ru/network.md) have the correct order.

**Comment by sfalexrog** [comment]
Do note that we had a pull request about that already (#131), but didn't translate the changes.
The russian version actually suggests performing `systemd daemon-reload` at some point. We should take another look at it - maybe just reversing the order is enough?

@hany606, you've accidentally commited a .swp file. Please remove it from the pull request (you can make a commit deleting this file).

**Comment by hany606** [comment]
@sfalexrog I have committed with deleting the .swp file. Reversing the order was enough with me with rebooting the raspberry pi in the end.

**Comment by sfalexrog** [comment]
Looks good to me!

**Comment by okalachev** [comment]
@hany606, note that you've created a PR from your `master` branch (which is not good usually).
As @sfalexrog squashed your commits into one, you're going to need to reset you `master` to upstream `master`.

**Pull request merged**
